<?php
/**
 * TL_ROOT/system/modules/PiwikTrackingTag/languages/cs/default.php 
 * 
 * Contao extension: PiwikTrackingTag 2.0.7 stable 
 * Czech translation file 
 * 
 * Copyright : Wangaz GbR 2010 
 * License   : LGPL 
 * Author    : Torben Stoffer (Torben) 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['ERR']['piwikPath'] = "Tato adresa URL není odkaz na piwik instalaci (Error: %s %s).";
 
?>
