<?php
/**
 * TL_ROOT/system/modules/PiwikTrackingTag/languages/cs/tl_layout.php 
 * 
 * Contao extension: PiwikTrackingTag 2.0.7 stable 
 * Czech translation file 
 * 
 * Copyright : Wangaz GbR 2010 
 * License   : LGPL 
 * Author    : Torben Stoffer (Torben) 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_layout']['piwik_legend'] = "Piwik tracking tag";
$GLOBALS['TL_LANG']['tl_layout']['piwikEnabled']['0'] = "Přidat Piwik tracking tag";
$GLOBALS['TL_LANG']['tl_layout']['piwikEnabled']['1'] = "Vloží do stránky sledovací kód pro software webové analytiky Piwik.";
$GLOBALS['TL_LANG']['tl_layout']['piwikCountAdmins']['0'] = "Přidat backend uživatele";
$GLOBALS['TL_LANG']['tl_layout']['piwikCountAdmins']['1'] = "Přidat do statistiky uživatele, kteří jsou přihlášeni do Contao (backend).";
$GLOBALS['TL_LANG']['tl_layout']['piwikCountUsers']['0'] = "Přidat frontend přihlášený uživatele";
$GLOBALS['TL_LANG']['tl_layout']['piwikCountUsers']['1'] = "Přidat do statistiky uživatele, kteří jsou přihlášeni na stránce (frontend).";
$GLOBALS['TL_LANG']['tl_layout']['piwikPath']['0'] = "URL k instalaci Piwik";
$GLOBALS['TL_LANG']['tl_layout']['piwikPath']['1'] = "Zadejte URL k intalaci Piwik (např. http://www.domena.cz/piwik/)";
$GLOBALS['TL_LANG']['tl_layout']['piwikSiteID']['0'] = "Piwik ID internetové stránky";
$GLOBALS['TL_LANG']['tl_layout']['piwikSiteID']['1'] = "Zadejte ID internetové stránky, který byl vytvořen v Piwik.";
$GLOBALS['TL_LANG']['tl_layout']['piwikPageName']['0'] = "Použijte název stránky";
$GLOBALS['TL_LANG']['tl_layout']['piwikPageName']['1'] = "Použijte název stránky, místo aliasů ve statistice.";
$GLOBALS['TL_LANG']['tl_layout']['piwik404']['0'] = "Přidat <em>404 Stránka nebyla nalezena</em>";
$GLOBALS['TL_LANG']['tl_layout']['piwik404']['1'] = "Zahrnout do statistiky Piwik odkazy na <em>404 Stránka nebyla nalezena</em>. Takže si můžete najít \"mrtvé odkazy\".";
 
?>
